services:
  - type: web
    name: play2earnx-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DB_HOST
        value: play2earnx-db
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: example
      - key: DB_NAME
        value: play2earnx
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DEBUG_SHOW_OTP
        value: true
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: "apache2-foreground"

  - type: pserv
    name: play2earnx-db
    env: docker
    dockerCommand: "mysqld"
    image: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: example
      - key: MYSQL_DATABASE
        value: play2earnx
    disk:
      name: data
      mountPath: /var/lib/mysql
      sizeGB: 1
